spring.application.name=oauth-meal
logging.level.org.springframework.security=TRACE
# database
spring.datasource.url=jdbc:postgresql://localhost/mydb
# spring.datasource.username=sa
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#oauth
spring.security.oauth2.client.registration.google.client-id=782702978750-ouejj2u1g0l61h1ete0gh5j4ofikf7g1.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
