spring.application.name=oauth-meal
logging.level.org.springframework.security=TRACE
# database
spring.datasource.url=jdbc:postgresql://localhost/mydb
# spring.datasource.username=sa
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
